"""
Export Router — Generate PDF reports and Markdown exports.
GET /export/{comparison_id}/pdf
GET /export/{comparison_id}/markdown
GET /export/{comparison_id}/executive
"""
import logging
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response, PlainTextResponse

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/{comparison_id}/markdown", response_class=PlainTextResponse)
async def export_markdown(comparison_id: str):
    """Export comparison as Markdown — copy/paste ready."""
    # In production: load from DB
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    md = f"""# CompareIQ AI — Comparison Report
**ID:** {comparison_id}
**Generated:** {now}
**Created by:** Raja Abimanyu N | Data Scientist | AI & Applied Machine Learning

---

## Executive Summary
[Summary would be loaded from DB]

## Winner Recommendation
🏆 **[Winner Name]** — Score: XX/100

### Why This Choice
[Rationale loaded from DB]

## Side-by-Side Comparison

| Criterion | Option A | Option B |
|-----------|----------|----------|
| Performance | 92 | 78 |
| Price | 75 | 88 |
| Build Quality | 90 | 82 |

## Contradictions Found
- [Contradiction details]

## Trust Metrics
- Confidence: 87%
- Completeness: 74%
- Freshness: 91%
- Contradictions: 2 found

---
*Generated by CompareIQ AI — Compare anything. Decide faster.*
"""
    return PlainTextResponse(content=md, media_type="text/markdown")


@router.get("/{comparison_id}/executive", response_class=PlainTextResponse)
async def export_executive_summary(comparison_id: str):
    """One-paragraph executive summary for stakeholder sharing."""
    summary = (
        f"CompareIQ AI Analysis [{comparison_id}]: Based on multi-source evidence across "
        "6 weighted criteria, Option A is recommended with a confidence score of 87%. "
        "Key advantages include superior performance and build quality. "
        "2 contradictions were detected between sources and flagged for review. "
        "Generated by CompareIQ AI — Raja Abimanyu N."
    )
    return PlainTextResponse(content=summary)


@router.get("/{comparison_id}/pdf")
async def export_pdf(comparison_id: str):
    """Generate a polished PDF report using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.units import cm
        import io

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()

        INDIGO = colors.HexColor("#6366f1")
        DARK = colors.HexColor("#1e293b")
        MUTED = colors.HexColor("#94a3b8")

        title_style = ParagraphStyle("Title", parent=styles["Heading1"], textColor=INDIGO, fontSize=22, spaceAfter=6)
        subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"], textColor=MUTED, fontSize=10, spaceAfter=20)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=DARK, fontSize=14, spaceAfter=8)
        body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14, spaceAfter=10)

        story = [
            Paragraph("◈ CompareIQ AI", title_style),
            Paragraph(f"Comparison Report — ID: {comparison_id}", subtitle_style),
            Paragraph("Executive Summary", h2_style),
            Paragraph("[Executive summary loaded from DB]", body_style),
            Spacer(1, 0.5*cm),
            Paragraph("Scoring Table", h2_style),
        ]

        table_data = [
            ["Criterion", "Option A", "Option B", "Advantage"],
            ["Performance", "92", "78", "Option A"],
            ["Price", "75", "88", "Option B"],
            ["Build Quality", "90", "82", "Option A"],
        ]
        t = Table(table_data, colWidths=[5*cm, 3*cm, 3*cm, 4*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)

        story.extend([
            Spacer(1, 0.8*cm),
            Paragraph("Created by Raja Abimanyu N | Data Scientist | AI & Applied Machine Learning", subtitle_style),
            Paragraph("Generated by CompareIQ AI — Compare anything. Decide faster.", subtitle_style),
        ])

        doc.build(story)
        pdf_bytes = buf.getvalue()

        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=compareiq_{comparison_id[:8]}.pdf"},
        )

    except ImportError:
        raise HTTPException(status_code=500, detail="ReportLab not installed. Run: pip install reportlab")
    except Exception as exc:
        logger.exception("PDF export failed: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))
